language: go
go:
- tip
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- go test -v -covermode=count -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
env:
  global:
    secure: QZ+hV9aEvtO5E/sCKbPGZhzCD0y0KXZk2THgGOUl6+dj1dAyuXvAmAAvzm+//NgXzvg0TITX0KpqjhMEn5q4VfemvaGyp4SUW/b+cr6xv7jmOKoQrZBMWyrSjSy4bIpohnrpOuRdzIvZ16eDKyiNbVsSenj+1e5iBHk77PsQRD7VjD7rGQtqFpf7dQuO6cR4K9Y8cSOFZkoicsENfb0EEZUfkCZr54oXom6l6KTnSksJ9beMVJYWIhuJ5SpUDjP7Zya3mub0lt/0YMA17pIk5F6TpOWa8Dp1ToAmBo4QtG4Y69GHpy6HzRmnuMJfNId2hu36gAKDmE5YH9WKGRPjXv9RERkQtufOg5EeiHkpyyemXapjf7+Tk7SrjV2ycpHBAtZkPozLVkIfTmxqgklhteU+y75tzNFxM1PU8LwGej4kJC16JgAlLU3g9fdUKEqy2iezaU4/n8dWjLA8pdky1TIVG8Rp54+SJAtUDA7iHZCsvRY/xqoXWAEWIJDFOPxS1P7fq0XywYmnM0H+ibOzwuB2Dwe8aTRhBWVVRVZHPLKEv2QZJMoW0L1m/tXyPawQH0bC7hSsfk7SIQ1N0lTnhmmfn327SM24ufLvM2ySTmPAqnkAiaBv31qOTBZ5wu/hhylz3A4JJgcNQDInU7S4QqdJCL/vufKBncdS2J3XHZY=

